title: 'Felquis Gimenes'
email: 'oi@felquis.com'
description: 'Diário de um Desenvolvedor Web'
sub_name: 'Web Developer'

baseurl: '/'
url: 'http://felquis.com'

excerpt_separator: '<!--more-->'

# paginate
paginate: 5
paginate_path: /page/:num

# exclude folders for ci
exclude: [vendor]

# permalink
permalink: :title/

sass:
    dir: _sass
    style: compressed

# Build settings
markdown: kramdown
